### ISSUE TITLE
draft-ietf-quic-multipath version

### ISSUE THREAD

**Issue by xuntyz** [Tencent/tquic#376]
Which draft version does the multipath transmission protocol used in tquic?

**Comment by iyangsj** [comment]
@xuntyz It is based on the [draft-ietf-quic-multipath-05](https://datatracker.ietf.org/doc/html/draft-ietf-quic-multipath-05) but doesn't fully adopt some of its complex designs. As you can see,[ later versions of the draft](https://datatracker.ietf.org/doc/html/draft-ietf-quic-multipath) simplified some of these complex designs, making them more concise and elegant. 

To ensure interoperability, you currently need to use tquic for both the client and the server. 

Since the design of multipath may still change significantly, we will support the latest version of the draft at an appropriate time.
